[project]
name = "gpt-oss-mcp-server"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.12.2",
    "httpx>=0.24.0",
    "beautifulsoup4>=4.12.0",
    "sqlalchemy>=2.0.0",
    "aiosqlite>=0.19.0",
    "qdrant-client>=1.7.0",
    "playwright>=1.40.0",
]
